### ISSUE TITLE
keychain GPGKEY appears not to work

### ISSUE THREAD

**Issue by phillord** [funtoo/keychain#56]
I've just updating from keychain 2.7.1 to take advantage of a bug fix. But the command line interface seems to have changed. In 2.7.1

      keychain DEADBEEF

seems to work fine for adding a GPG key. While in 2.8.2 I have to do

     keychain --agents gpg DEADBEEF

Otherwise, I get the slightly obscure "can't find DEADBEEF; skipping" warning.

Fantastic tool BTW, been using it for years.

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-3141

**Comment by angryvincent** [comment]
this looks like documentation need changes, not really a defect?

**Comment by phillord** [comment]
I'm easy whether it is considered to be a defect in documentation or software. Although, given that ssh keys are a file location and GPG a numeric ID, the older behaviour seems nicer from a user perspective.  Why ask for something you can work out?

**Comment by bon** [comment]
@phillord +1

**Comment by angryvincent** [comment]
starting with keychain 2.7.2 gpg key addition has changed because of this: https://bugs.funtoo.org/browse/FL-374
This change is also described in docs. 
http://git.funtoo.org/keychain/commit/?id=6585bce6fc62ef0db958d3a9ee7eecf254270d9e
http://git.funtoo.org/keychain/commit/?id=e4754b3306eaf161c317320fdaf3388ff20ac6fa

**Comment by danielrobbins** [comment]
This issue has been resolved in the Funtoo Linux bug tracker. Closing on GitHub.

**Comment by bon** [comment]
This is not the same issue. The funtoo issue addresses gpg being started up whether it is needed or not. The current issue concerns how keychain needs to be called. The problem remains in version 2.8.2.
